"""Group D - known weaknesses of jev-1.13: counting, number_compare, date_compare,
two_hop, double_negation. All synthetic with code-computed gold labels."""

import datetime
import random

from probes_common import SEED, write_task

N = 150

# --------------------------------------------------------------------------- counting
FRUITS = ["apple", "banana", "mango", "pear", "peach", "plum", "cherry", "grape",
          "lemon", "orange", "apricot", "papaya", "kiwi", "fig", "pineapple",
          "strawberry", "raspberry", "blueberry", "watermelon", "mandarin"]
NOT_FRUITS = ["hammer", "chair", "river", "pencil", "tiger", "cloud", "bottle",
              "ladder", "violin", "carrot", "potato", "onion", "lettuce", "spoon",
              "window", "guitar", "rabbit", "mountain", "blanket", "teacher",
              "cabbage", "hallway", "engine", "candle", "bicycle", "spinach"]


def build_counting():
    rng = random.Random(SEED)
    items = []
    for i in range(N):
        n = rng.randint(6, 14)
        k = rng.randint(0, min(10, n))
        words = rng.sample(FRUITS, k) + rng.sample(NOT_FRUITS, n - k)
        rng.shuffle(words)
        items.append({
            "id": f"counting-{i}",
            "state": {"items": words},
            "gold": f"n{k}",
            "meta": {"list_length": n},
        })
    write_task({
        "id": "counting",
        "title": "Counting fruits in a list",
        "category": "known_weakness",
        "source": "synthetic, generated by code with seed 7 from fixed fruit / non-fruit word lists; gold is the code-computed count",
        "primitive": "choice",
        "metric": "accuracy",
        "question": {
            "type": "choice",
            "instructions": (
                "`items` is a list of common English words. Count how many entries of "
                "`items` name a fruit (a sweet edible fruit in ordinary everyday usage, "
                "not the botanical sense). Answer with the option for that count."
            ),
            "criteria": {f"n{c}": f"Exactly {c} of the entries in `items` name a fruit."
                         for c in range(11)},
        },
        "items": items,
    })


# --------------------------------------------------------------- number_compare
TRICKY = [
    ("9.11", "9.9"), ("9.9", "9.11"), ("8.7", "8.65"), ("8.65", "8.7"),
    ("1,000,000", "999,999"), ("999,999", "1,000,000"), ("0.5", "0.45"),
    ("0.45", "0.5"), ("12.3", "12.30"), ("3.14", "3.9"), ("10.10", "10.9"),
    ("2.100", "2.2"), ("100,000", "99,999"), ("-3.5", "-3.45"), ("-3.45", "-3.5"),
    ("0.1", "0.09"), ("7.07", "7.7"), ("15.5", "15.45"), ("1,250", "1249.75"),
    ("5.0", "5"), ("20.20", "20.9"), ("4.999", "5.01"), ("-0.5", "-0.45"),
    ("6.30", "6.3"), ("11.11", "11.9"),
]


def _num(s):
    return float(s.replace(",", ""))


def build_number_compare():
    rng = random.Random(SEED)
    pairs = list(TRICKY)
    while len(pairs) < N + 20:
        style = rng.randrange(4)
        if style == 0:
            base = rng.randint(1, 999)
            a, b = f"{base}", f"{base + rng.choice([-2, -1, 1, 2])}"
        elif style == 1:
            w = rng.randint(1, 40)
            a = f"{w}.{rng.randint(1, 9)}"
            b = f"{w}.{rng.randint(10, 99)}"
            if rng.random() < 0.5:
                a, b = b, a
        elif style == 2:
            base = rng.randint(100000, 9999999)
            other = base + rng.choice([-1, 1, -10, 10])
            a = f"{base:,}"
            b = f"{other:,}"
        else:
            a = f"{rng.uniform(0, 100):.2f}"
            b = f"{rng.uniform(0, 100):.3f}"
        if _num(a) == _num(b):
            continue
        pairs.append((a, b))
    pairs = [p for p in pairs if _num(p[0]) != _num(p[1])][:N]
    assert len(pairs) == N
    # keep the true/false split even without touching the values: swap a and b where needed
    order = list(range(N))
    rng.shuffle(order)
    want_true = set(order[: N // 2])
    items = []
    for i, (a, b) in enumerate(pairs):
        if _num(a) == _num(b):
            continue
        if (_num(a) > _num(b)) != (i in want_true):
            a, b = b, a
        items.append({
            "id": f"number_compare-{i}",
            "state": {"a": a, "b": b},
            "gold": _num(a) > _num(b),
        })
    write_task({
        "id": "number_compare",
        "title": "Numeric comparison of similar magnitudes",
        "category": "known_weakness",
        "source": "synthetic, generated by code with seed 7; 25 hand-picked tricky pairs (9.11 vs 9.9, 1,000,000 vs 999,999, ...) plus generated near-magnitude pairs; gold computed in code, balanced true/false",
        "primitive": "noul",
        "metric": "accuracy",
        "question": {
            "type": "noul",
            "instructions": (
                "`a` and `b` are two numbers written as text. A comma in a number is a "
                "thousands separator and a full stop is the decimal point. Read both as "
                "numeric values. Is `a` strictly greater than `b`?"
            ),
            "criteria": {
                "true": "The numeric value of `a` is strictly greater than the numeric value of `b`.",
                "false": "The numeric value of `a` is less than or equal to the numeric value of `b`.",
            },
        },
        "items": items,
    })


# ----------------------------------------------------------------- date_compare
MONTHS = ["January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December"]


def _last_day(y, m):
    if m == 12:
        return datetime.date(y, 12, 31)
    return datetime.date(y, m + 1, 1) - datetime.timedelta(days=1)


def _formats(d, rng):
    """Return (rendered text, note) for a date, in one of several mixed formats."""
    style = rng.randrange(5)
    if style == 0:
        return d.isoformat(), None
    if style == 1:
        return f"{d.day} {MONTHS[d.month - 1]} {d.year}", None
    if style == 2:
        return (f"{d.month:02d}/{d.day:02d}/{str(d.year)[2:]}",
                "US convention: dates written as NN/NN/NN are month/day/two-digit-year.")
    if style == 3:
        return f"{MONTHS[d.month - 1]} {d.day}, {d.year}", None
    last = _last_day(d.year, d.month)
    if d == last:
        return f"the last day of {MONTHS[d.month - 1]} {d.year}", None
    return d.isoformat(), None


def build_date_compare():
    rng = random.Random(SEED)
    items = []
    i = 0
    while len(items) < N:
        y = rng.choice([2023, 2024, 2025])
        m = rng.randint(1, 12)
        d1 = datetime.date(y, m, rng.randint(1, 28))
        if rng.random() < 0.3:
            d1 = _last_day(y, m)
        delta = rng.choice([1, 2, 3, 5, 10, 20, 30, 45, 90, 200, 365])
        d2 = d1 + datetime.timedelta(days=delta * rng.choice([-1, 1]))
        if d1 == d2:
            continue
        want_true = len(items) % 2 == 0
        if (d1 < d2) != want_true:
            d1, d2 = d2, d1
        a, na = _formats(d1, rng)
        b, nb = _formats(d2, rng)
        notes = " ".join(sorted({n for n in (na, nb) if n}))
        state = {"a": a, "b": b}
        if notes:
            state["format_note"] = notes
        items.append({
            "id": f"date_compare-{i}",
            "state": state,
            "gold": d1 < d2,
            "meta": {"a_iso": d1.isoformat(), "b_iso": d2.isoformat()},
        })
        i += 1
    write_task({
        "id": "date_compare",
        "title": "Date comparison across mixed formats",
        "category": "known_weakness",
        "source": "synthetic, generated by code with seed 7; calendar dates rendered in mixed formats (2024-03-05, 5 March 2024, 03/05/24 US-style with the convention stated in the state, 'the last day of February 2024'); gold computed in code, balanced true/false",
        "primitive": "noul",
        "metric": "accuracy",
        "question": {
            "type": "noul",
            "instructions": (
                "`a` and `b` each describe one calendar date, possibly in different "
                "formats. If `format_note` is present, it tells you how to read an "
                "ambiguous format. Is the date described by `a` strictly earlier in the "
                "calendar than the date described by `b`?"
            ),
            "criteria": {
                "true": "The calendar date given by `a` falls before the calendar date given by `b`.",
                "false": "The calendar date given by `a` falls on or after the calendar date given by `b`.",
            },
        },
        "items": items,
    })


# ---------------------------------------------------------------------- two_hop
NAMES = ["Ann", "Bob", "Carla", "Dan", "Elena", "Farid", "Grace", "Hugo", "Iris",
         "Jonas", "Kira", "Liam", "Mona", "Nils", "Omar", "Petra", "Quinn", "Rosa",
         "Samir", "Tara", "Ugo", "Vera", "Wes", "Xenia", "Yara", "Zeno"]
CITIES = ["Lyon", "Oslo", "Porto", "Bilbao", "Utrecht", "Gdansk", "Bergen", "Verona",
          "Malmo", "Cork", "Graz", "Leeds", "Turku", "Ghent", "Split", "Bari"]
TEAMS = ["the audit team", "the payroll team", "the logistics team", "the design team",
         "the support team", "the research team", "the field team", "the legal team"]


def build_two_hop():
    rng = random.Random(SEED)
    items = []
    for i in range(N):
        people = rng.sample(NAMES, 8)
        cities = rng.sample(CITIES, 6)
        subject, manager = people[0], people[1]
        answer_city = cities[0]
        facts = [
            f"{subject}'s manager is {manager}.",
            f"{manager}'s office is in {answer_city}.",
        ]
        # distractors: other people's managers and offices, including one for the subject
        facts.append(f"{subject}'s office is in {cities[1]}.")
        for k in range(2, 6):
            p, q = people[k], people[(k + 3) % 8]
            facts.append(f"{p}'s manager is {q}.")
        for k, c in enumerate(cities[2:6]):
            facts.append(f"{people[k + 2]}'s office is in {c}.")
        facts.append(f"{rng.choice(TEAMS).capitalize()} reports to {people[4]}.")
        facts = facts[: rng.randint(7, 9)] + facts[-1:]
        rng.shuffle(facts)
        options = [answer_city] + rng.sample([c for c in cities[1:]], 3)
        rng.shuffle(options)
        items.append({
            "id": f"two_hop-{i}",
            "state": {"facts": facts, "person": subject},
            "questions": {"q": {
                "type": "choice",
                "instructions": (
                    "`facts` is an unordered list of statements about people, their "
                    "managers and their office cities. First find who `person`'s manager "
                    "is, then find the city that manager's office is in. In which city "
                    "is the office of `person`'s manager?"
                ),
                "criteria": {c: f"The office of `person`'s manager is in {c}." for c in options},
            }},
            "gold": {"q": answer_city},
            "meta": {"manager": manager},
        })
    write_task({
        "id": "two_hop",
        "title": "Two-hop relational lookup with distractors",
        "category": "known_weakness",
        "source": "synthetic, generated by code with seed 7; 2-hop manager/office facts plus 6-8 distractor facts (including the subject's own office city); gold computed in code",
        "primitive": "choice",
        "metric": "accuracy",
        "items": items,
    })


# --------------------------------------------------------------- double_negation
POLICIES = [
    ("refunds are allowed more than 30 days after purchase",
     "A customer asks for a refund 45 days after purchase."),
    ("staff are permitted to work from home on Fridays",
     "A staff member plans to work from home this Friday."),
    ("guests may bring pets into the lobby",
     "A guest wants to walk into the lobby with their dog."),
    ("students are allowed to retake the final exam",
     "A student asks to retake the final exam."),
    ("contractors are permitted to park in the visitor lot",
     "A contractor wants to park in the visitor lot."),
    ("members may transfer their season ticket to another person",
     "A member wants to give their season ticket to a friend."),
    ("passengers are allowed to carry liquids over 100 ml in the cabin",
     "A passenger wants to take a 250 ml bottle into the cabin."),
    ("tenants are permitted to sublet the apartment",
     "A tenant wants to sublet the apartment for the summer."),
    ("photography is allowed inside the exhibition hall",
     "A visitor wants to photograph a painting in the exhibition hall."),
    ("employees may expense meals over 50 euros",
     "An employee submits a 70 euro dinner receipt as an expense."),
]


def _render(clause, negations, rng):
    if negations == 0:
        return clause[0].upper() + clause[1:] + "."
    if negations == 1:
        if rng.random() < 0.5:
            neg = clause.replace(" are allowed", " are not allowed") \
                        .replace(" are permitted", " are not permitted") \
                        .replace(" may ", " may not ") \
                        .replace(" is allowed", " is not allowed")
            assert neg != clause, clause
            return neg[0].upper() + neg[1:] + "."
        return f"It is not the case that {clause}."
    inner = clause.replace(" are allowed", " are not allowed") \
                  .replace(" are permitted", " are not permitted") \
                  .replace(" may ", " may not ") \
                  .replace(" is allowed", " is not allowed")
    assert inner != clause, clause
    return f"It is not the case that {inner}."


def build_double_negation():
    rng = random.Random(SEED)
    items = []
    # balance gold: 75 items with an odd number of negations (not allowed),
    # 75 with an even number (allowed, split between 0 and 2 negations)
    plan = [1] * 75 + [0] * 37 + [2] * 38
    rng.shuffle(plan)
    for i in range(N):
        clause, action = POLICIES[i % len(POLICIES)]
        negations = plan[i]
        policy = _render(clause, negations, rng)
        items.append({
            "id": f"double_negation-{i}",
            "state": {"policy": policy, "action": action},
            "gold": negations % 2 == 0,
            "meta": {"negations": negations},
        })
    write_task({
        "id": "double_negation",
        "title": "Permission under zero, one and two negations",
        "category": "known_weakness",
        "source": "synthetic, generated by code with seed 7; 10 base policy clauses rendered with 0, 1 or 2 negations; gold is the code-computed parity of the negations",
        "primitive": "noul",
        "metric": "accuracy",
        "question": {
            "type": "noul",
            "instructions": (
                "`policy` is a single policy sentence and `action` describes something a "
                "person wants to do. Read `policy` literally, including any negations it "
                "contains. Does `policy` permit the action described in `action`?"
            ),
            "criteria": {
                "true": "Read literally, `policy` says the action in `action` is allowed.",
                "false": "Read literally, `policy` says the action in `action` is not allowed.",
            },
        },
        "items": items,
    })


if __name__ == "__main__":
    build_counting()
    build_number_compare()
    build_date_compare()
    build_two_hop()
    build_double_negation()
